namespace Apps.DeepL.Constants;

public static class LanguageConstants
{
    public static Dictionary<string, string> TargetLanguages => new()
    {
        { "AR", "Arabic" },
        { "BG", "Bulgarian" },
        { "CS", "Czech" },
        { "DA", "Danish" },
        { "DE", "German" },
        { "EL", "Greek" },
        { "EN", "English" },
        { "ES", "Spanish" },
        { "ET", "Estonian" },
        { "FI", "Finnish" },
        { "FR", "French" },
        { "HU", "Hungarian" },
        { "ID", "Indonesian" },
        { "IT", "Italian" },
        { "JA", "Japanese" },
        { "KO", "Korean" },
        { "LT", "Lithuanian" },
        { "LV", "Latvian" },
        { "NB", "Norwegian Bokmål" },
        { "NL", "Dutch" },
        { "PL", "Polish" },
        { "PT", "Portuguese (unspecified variant)" },
        { "RO", "Romanian" },
        { "RU", "Russian" },
        { "SK", "Slovak" },
        { "SL", "Slovenian" },
        { "SV", "Swedish" },
        { "TR", "Turkish" },
        { "UK", "Ukrainian" },
        { "ZH", "Chinese (unspecified variant)" },
        { "DE-CH", "German (Swiss)" },
        { "EN-GB", "English (British)" },
        { "EN-US", "English (American)" },
        { "FR-CA", "French (Canadian)" },
        { "PT-BR", "Portuguese (Brazilian)" },
        { "PT-PT", "Portuguese (European)" },
        { "ZH-HANS", "Chinese (simplified)" },
        { "ZH-HANT", "Chinese (traditional)" },
        { "ES-419", "Spanish (Latin American)" },
        { "ACE", "Acehnese" },
        { "AF", "Afrikaans" },
        { "AN", "Aragonese" },
        { "AS", "Assamese" },
        { "AY", "Aymara" },
        { "AZ", "Azerbaijani" },
        { "BA", "Bashkir" },
        { "BE", "Belarusian" },
        { "BHO", "Bhojpuri" },
        { "BN", "Bengali" },
        { "BR", "Breton" },
        { "BS", "Bosnian" },
        { "CA", "Catalan" },
        { "CEB", "Cebuano" },
        { "CKB", "Kurdish (Sorani)" },
        { "CY", "Welsh" },
        { "EO", "Esperanto" },
        { "EU", "Basque" },
        { "FA", "Persian" },
        { "GA", "Irish" },
        { "GL", "Galician" },
        { "GN", "Guarani" },
        { "GOM", "Konkani" },
        { "GU", "Gujarati" },
        { "HA", "Hausa" },
        { "HE", "Hebrew" },
        { "HI", "Hindi" },
        { "HR", "Croatian" },
        { "HT", "Haitian Creole" },
        { "HY", "Armenian" },
        { "IG", "Igbo" },
        { "IS", "Icelandic" },
        { "JV", "Javanese" },
        { "KA", "Georgian" },
        { "KK", "Kazakh" },
        { "KMR", "Kurdish (Kurmanji)" },
        { "KY", "Kyrgyz" },
        { "LA", "Latin" },
        { "LB", "Luxembourgish" },
        { "LMO", "Lombard" },
        { "LN", "Lingala" },
        { "MAI", "Maithili" },
        { "MG", "Malagasy" },
        { "MI", "Maori" },
        { "MK", "Macedonian" },
        { "ML", "Malayalam" },
        { "MN", "Mongolian" },
        { "MR", "Marathi" },
        { "MS", "Malay" },
        { "MT", "Maltese" },
        { "MY", "Burmese" },
        { "NE", "Nepali" },
        { "OC", "Occitan" },
        { "OM", "Oromo" },
        { "PA", "Punjabi" },
        { "PAG", "Pangasinan" },
        { "PAM", "Kapampangan" },
        { "PRS", "Dari" },
        { "PS", "Pashto" },
        { "QU", "Quechua" },
        { "SA", "Sanskrit" },
        { "SCN", "Sicilian" },
        { "SQ", "Albanian" },
        { "SR", "Serbian" },
        { "ST", "Sesotho" },
        { "SU", "Sundanese" },
        { "SW", "Swahili" },
        { "TA", "Tamil" },
        { "TE", "Telugu" },
        { "TG", "Tajik" },
        { "TH", "Thai" },
        { "TK", "Turkmen" },
        { "TL", "Tagalog" },
        { "TN", "Tswana" },
        { "TS", "Tsonga" },
        { "TT", "Tatar" },
        { "UR", "Urdu" },
        { "UZ", "Uzbek" },
        { "VI", "Vietnamese" },
        { "WO", "Wolof" },
        { "XH", "Xhosa" },
        { "YI", "Yiddish" },
        { "YUE", "Cantonese" },
        { "ZU", "Zulu" },
    };

    public static Dictionary<string, string> WriteLanguages => new()
    {
        { "de", "German" },
        { "en-GB", "British English" },
        { "en-US", "American English" },
        { "es", "Spanish" },
        { "fr", "French" },
        { "it", "Italian" },
        { "pt-BR", "Brazilian Portuguese" },
        { "pt-PT", "Portuguese" }
    };
}